# Generated by Django 4.2.2 on 2023-06-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_proof',
            new_name='service',
        ),
    ]
