# Generated by Django 4.2.2 on 2023-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_id_proof_client_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
