# Generated by Django 4.2.2 on 2023-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_appointment'),
        ('client', '0003_remove_client_address_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='appointments',
            field=models.ManyToManyField(null=True, related_name='clients', to='appointment.appointment'),
        ),
    ]
