# Generated by Django 4.2.2 on 2023-06-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='appointments',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
    ]
