# Generated by Django 4.2.1 on 2023-06-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
